version: '3.3'

services:
  back-end:
    container_name: back-end
    image: back-end:1.0
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "db"

  front-end:
    container_name: front-end
    image: front-end:1.0
    restart: always
    ports:
      - 3000:3000