services:

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  backend:
    build: ./back-end
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - tictactoe-postgres-db-deply 
    networks:
      - app_network
    environment:
      VIRTUAL_HOST: backend.iampedrovieira.pt

  frontend:
    build: ./front-end/tic-tac-toe
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - app_network
    environment:
      VIRTUAL_HOST: tictactoe.iampedrovieira.pt
  
  tictactoe-postgres-db-deply:
    image: postgres
    container_name: tictactoe-postgres-db-deply
    environment:
      POSTGRES_DB: tictactoe-aws
      POSTGRES_USER: osvaldinho
      POSTGRES_PASSWORD: tgarciaw
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app_network
  
networks:
  app_network:
    driver: bridge